version: '3.7'

services:
  db:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_DB: bitcoin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    ports:
      - "5432:5432"
  # application:
  #   container_name: anymind
  #   image: anymind:latest
  #   depends_on:
  #     - db
  #   ports:
  #     - 9997:9997